---
version: '3'
services:
  adm:
    restart: always
    build: .
    command: python manage.py runserver 0.0.0.0:8080
    env_file:
      - .env
    networks:
      - practiqa
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.adm.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.adm.entrypoints=websecure"
      - "traefik.http.routers.adm.tls.certresolver=myresolver"

networks:
  practiqa:
    external: true
